#pragma once
#include <lib/interpreter/ast/literal.hpp>
#include <lib/interpreter/ast/sum.hpp>
#include <lib/interpreter/ast/var.hpp>
#include <lib/interpreter/ast/scope.hpp>
#include <lib/interpreter/ast/return.hpp>
#include <lib/interpreter/ast/function.hpp>
#include <lib/interpreter/ast/module.hpp>
#include <lib/interpreter/ast/type.hpp>
