name: cpp-linter

on:
  pull_request:
    types: [opened, reopened]  # let PR-synchronize events be handled by push events
  push:

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v1.4.5
        id: linter
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          style: file
          version: 14
